# Generated by Django 5.0.1 on 2024-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_navbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='navigation',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigation',
            name='type',
            field=models.CharField(choices=[('nav-item', 'Nav Item'), ('nav-item dropdown', 'Nav Item Drop')], default='nav-item', max_length=50),
        ),
        migrations.AddField(
            model_name='navigation',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddConstraint(
            model_name='navigation',
            constraint=models.UniqueConstraint(fields=('order',), name='order must be uniqe'),
        ),
    ]
