# Generated by Django 5.0.6 on 2024-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_navbar', '0006_navigationlogo_delete_navlogo_alter_navigation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='name_de',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='type',
            field=models.CharField(choices=[('nav-item', 'Nav Item'), ('nav-item dropdown', 'Nav Item Drop'), ('dropdown-item', 'Drop Down Item')], default='nav-item', max_length=50, verbose_name='type'),
        ),
    ]
