# Generated by Django 5.0.6 on 2024-06-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_navbar', '0008_alter_navigation_options_navigationdropdown_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='name_af',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ar',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ar_dz',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ast',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_az',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_be',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_bg',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_bn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_br',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_bs',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ca',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ckb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_cs',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_cy',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_da',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_dsb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_el',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_en_au',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_en_gb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_eo',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es_ar',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es_co',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es_mx',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es_ni',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_es_ve',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_et',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_eu',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_fa',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_fi',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_fr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_fy',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ga',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_gd',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_gl',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_he',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_hi',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_hr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_hsb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_hu',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_hy',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ia',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ig',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ind',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_io',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_is',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_it',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ja',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ka',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_kab',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_kk',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_km',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_kn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ko',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ky',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_lb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_lt',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_lv',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_mk',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ml',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_mn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_mr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ms',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_my',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_nb',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ne',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_nl',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_nn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_os',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_pa',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_pl',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_pt',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_pt_br',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ro',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ru',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sk',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sl',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sq',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sr_latn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sv',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_sw',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ta',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_te',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_tg',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_th',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_tk',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_tr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_tt',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_udm',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ug',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_uk',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_ur',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_uz',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_vi',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_zh_hans',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name_zh_hant',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_af',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ar_dz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ast',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_az',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_be',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_bg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_bn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_bs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ca',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ckb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_cs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_cy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_da',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_dsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_el',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_en_au',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_en_gb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_eo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es_co',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es_mx',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es_ni',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_es_ve',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_et',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_eu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_fa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_fi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_fr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_fy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ga',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_gd',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_gl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_he',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_hi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_hr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_hsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_hu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_hy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ig',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ind',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_io',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_is',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_it',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ja',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ka',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_kab',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_kk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_km',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_kn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ko',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ky',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_lb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_lt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_lv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_mk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ml',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_mn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_mr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ms',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_my',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_nb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ne',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_nl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_nn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_os',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_pa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_pl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_pt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_pt_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ro',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sq',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sr_latn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_sw',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ta',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_te',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_tg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_th',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_tk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_tr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_tt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_udm',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ug',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_uk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_ur',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_vi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_zh_hans',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationdropdown',
            name='name_zh_hant',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_af',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ar_dz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ast',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_az',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_be',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_bg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_bn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_bs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ca',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ckb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_cs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_cy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_da',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_dsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_el',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_en_au',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_en_gb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_eo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es_co',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es_mx',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es_ni',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_es_ve',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_et',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_eu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_fa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_fi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_fr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_fy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ga',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_gd',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_gl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_he',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_hi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_hr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_hsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_hu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_hy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ig',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ind',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_io',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_is',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_it',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ja',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ka',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_kab',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_kk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_km',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_kn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ko',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ky',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_lb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_lt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_lv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_mk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ml',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_mn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_mr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ms',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_my',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_nb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ne',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_nl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_nn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_os',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_pa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_pl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_pt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_pt_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ro',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sq',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sr_latn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_sw',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ta',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_te',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_tg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_th',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_tk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_tr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_tt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_udm',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ug',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_uk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_ur',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_vi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_zh_hans',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='alt_text_zh_hant',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_af',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ar_dz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ast',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_az',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_be',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_bg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_bn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_bs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ca',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ckb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_cs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_cy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_da',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_dsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_el',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_en_au',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_en_gb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_eo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es_co',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es_mx',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es_ni',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_es_ve',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_et',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_eu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_fa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_fi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_fr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_fy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ga',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_gd',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_gl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_he',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_hi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_hr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_hsb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_hu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_hy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ig',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ind',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_io',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_is',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_it',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ja',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ka',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_kab',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_kk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_km',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_kn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ko',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ky',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_lb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_lt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_lv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_mk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ml',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_mn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_mr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ms',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_my',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_nb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ne',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_nl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_nn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_os',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_pa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_pl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_pt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_pt_br',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ro',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sq',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sr_latn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sv',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_sw',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ta',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_te',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_tg',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_th',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_tk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_tr',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_tt',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_udm',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ug',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_uk',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_ur',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_vi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_zh_hans',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationlogo',
            name='name_zh_hant',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navigationdropdown',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DropDownRelation', to='django_navbar.navigation'),
        ),
    ]
